local colors = require("ui.themer").colorscheme("vivid")

return {
  CmpItemAbbr = { fg = colors.white },
  CmpItemAbbrDeprecated = { fg = colors.grey00, strikethrough = true },
  CmpItemAbbrMatch = { fg = colors.blue, bold = true },
  CmpBorder = { fg = colors.grey00 },
  CmpDocBorder = { fg = colors.grey00, bg = colors.base02 },
  CmpPmenu = { bg = colors.base02 },
  CmpItemKindConstant = { fg = colors.base09 },
  CmpItemKindFunction = { fg = colors.base0D },
  CmpItemKindIdentifier = { fg = colors.base08 },
  CmpItemKindField = { fg = colors.base08 },
  CmpItemKindVariable = { fg = colors.base0E },
  CmpItemKindSnippet = { fg = colors.red },
  CmpItemKindText = { fg = colors.base0B },
  CmpItemKindStructure = { fg = colors.base0E },
  CmpItemKindType = { fg = colors.base0A },
  CmpItemKindKeyword = { fg = colors.base07 },
  CmpItemKindMethod = { fg = colors.base0D },
  CmpItemKindConstructor = { fg = colors.blue },
  CmpItemKindFolder = { fg = colors.base07 },
  CmpItemKindModule = { fg = colors.base0A },
  CmpItemKindProperty = { fg = colors.base08 },
  CmpItemKindUnit = { fg = colors.base0E },
  CmpItemKindFile = { fg = colors.base07 },
  CmpItemKindColor = { fg = colors.red },
  CmpItemKindReference = { fg = colors.base05 },
  CmpItemKindStruct = { fg = colors.base0E },
  CmpItemKindOperator = { fg = colors.base05 },
  CmpItemKindTypeParameter = { fg = colors.base08 },
  CmpItemKindCopilot = { fg = colors.green },
}
