local colors = require("ui.themer").colorscheme("vivid")
return {
  DevIconDefault = { fg = colors.red },
  DevIconc = { fg = colors.blue },
  DevIconcss = { fg = colors.blue },
  DevIcondeb = { fg = colors.cyan },
  DevIconDockerfile = { fg = colors.cyan },
  DevIconhtml = { fg = colors.pink },
  DevIconjpeg = { fg = colors.magenta },
  DevIconjpg = { fg = colors.magenta },
  DevIconjs = { fg = colors.yellow },
  DevIconkt = { fg = colors.orange },
  DevIconlock = { fg = colors.red },
  DevIconlua = { fg = colors.blue },
  DevIconmp3 = { fg = colors.white },
  DevIconmp4 = { fg = colors.white },
  DevIconout = { fg = colors.white },
  DevIconpng = { fg = colors.magenta },
  DevIconpy = { fg = colors.cyan },
  DevIcontoml = { fg = colors.blue },
  DevIconts = { fg = colors.green01 },
  DevIconttf = { fg = colors.white },
  DevIconrb = { fg = colors.pink },
  DevIconrpm = { fg = colors.orange },
  DevIconvue = { fg = colors.green },
  DevIconwoff = { fg = colors.white },
  DevIconwoff2 = { fg = colors.white },
  DevIconxz = { fg = colors.yellow },
  DevIconzip = { fg = colors.yellow },
  DevIconZig = { fg = colors.orange },
}

